// REQUIRES SsboBufferBindings.comp
// REQUIRES CrossShaderUniformLocations
// REQUIRES MyVertex.comp


// should be the number of particles * 2 (two vertices per line)
layout(location = UNIFORM_LOCATION_PARTICLE_VELOCITY_VECTOR_GEOMETRY_BUFFER_SIZE) uniform uint uParticleVelocityVectorGeometryBufferSize;

/*-----------------------------------------------------------------------------------------------
Description:
    The SSBO that will contain all the vertices necessary to draw the velocity vector for each 
    particle.
Creator:    John Cox, 6/2017
-----------------------------------------------------------------------------------------------*/
layout (std430, binding = PARTICLE_VELOCITY_VECTOR_GEOMETRY_BUFFER_BINDING) buffer ParticleVelocityVectorGeometryBuffer
{
    MyVertex AllParticleVelocityVectorVertices[];
};