// REQUIRES SsboBufferBindings.comp
// REQUIRES CrossShaderUniformLocations
// REQUIRES MaxNumPotentialCollisions.comp


/*------------------------------------------------------------------------------------------------
Description:   
    Stores enough space for a single particle to have its own record about how many other 
    particles' bounding boxes overlapped with its own.  

    Filled in DetectCollisions.comp.
    Read in ResolveCollisions.comp.
Creator:    John Cox, 6/2017
------------------------------------------------------------------------------------------------*/
struct ParticlePotentialCollisions
{
    int _numPotentialCollisions;
    int _particleIndexes[MAX_NUM_POTENTIAL_COLLISIONS];
};


// should be 1 for each particle
layout(location = UNIFORM_LOCATION_PARTICLE_POTENTIAL_COLLISIONS_BUFFER_SIZE) uniform uint uParticlePotentialCollisionsBufferSize;

/*-----------------------------------------------------------------------------------------------
Description:
    Nothing special to say about this.  It's the buffer.
Creator:    John Cox, 6/2017
-----------------------------------------------------------------------------------------------*/
layout (std430, binding = PARTICLE_POTENTIAL_COLLISIONS_BUFFER_BINDING) buffer ParticlePotentialCollisionsBuffer
{
    ParticlePotentialCollisions AllParticlePotentialCollisions[];
};


