// REQUIRES SsboBufferBindings.comp
// REQUIRES CrossShaderUniformLocations


/*------------------------------------------------------------------------------------------------
Description:
    See description in ParticleMortonCode.h.
Creator:    John Cox, 5/2017
------------------------------------------------------------------------------------------------*/
struct ParticleMortonCode
{
    unsigned int _mortonCode;
    int _preSortedParticleIndex;

    // no GLSL-native structures, so no padding necessary on the CPU side
};

// expected to be the size of uMaxNumParticles
layout(location = UNIFORM_LOCATION_MAX_NUM_PARTICLE_MORTON_CODES) uniform uint uMaxNumParticleMortonCodes;

// these are swapped on each loop of the parallel sort routine
layout(location = UNIFORM_LOCATION_PARTICLE_MORTON_CODE_BUFFER_READ_OFFSET) uniform uint uParticleMortonCodeBufferReadOffset;
layout(location = UNIFORM_LOCATION_PARTICLE_MORTON_CODE_BUFFER_WRITE_OFFSET) uniform uint uParticleMortonCodeBufferWriteOffset;

/*------------------------------------------------------------------------------------------------
Description:
    See description in ParticleMortonCodeSsbo.h.
Creator:    John Cox, 5/2017
------------------------------------------------------------------------------------------------*/
layout (std430, binding = PARTICLE_MORTON_CODE_BUFFER_BINDING) buffer ParticleMortonCodeBuffer
{
    ParticleMortonCode AllParticleMortonCodes[];
};
