/*------------------------------------------------------------------------------------------------
Description:
    This value is used by bother CountNearbyParticles.comp for the loop limits and by 
    ParticleRender.vert for the color blending.
Creator:    John Cox, 4/2017
------------------------------------------------------------------------------------------------*/

// TODO: remove this file

#define NUM_PARTICLES_TO_CHECK_ON_EACH_SIDE 2
