// TODO: delete

//// REQUIRES SsboBufferBindings.comp
//// REQUIRES CrossShaderUniformLocations
//// REQUIRES MyVertex.comp
//
///*-----------------------------------------------------------------------------------------------
//Description:
//    This is a simple structure that describes the face of a 2D polygon.  Useful for making the 
//    code that uses the buffer and the vertices more readable.
//Creator:    John Cox (9-8-2016)
//-----------------------------------------------------------------------------------------------*/
//struct PolygonFace
//{
//    MyVertex _start;
//    MyVertex _end;
//
//    // just using vec4's so everything is already aligned to 16bytes and no padding necessary
//};
//
//// whatever size the user wants
//layout(location = UNIFORM_LOCATION_POLYGON_BUFFER_SIZE) uniform uint uMaxPolygons;
//
///*-----------------------------------------------------------------------------------------------
//Description:
//    The SSBO that will contain all polygons necessary to draw the quad tree.  For this demo, it 
//    is only 2D, so each face only contains two vertexes;
//Creator: John Cox (9-25-2016)
//-----------------------------------------------------------------------------------------------*/
//layout (std430, binding = POLYGON_BUFFER_BINDING) buffer PolygonBuffer
//{
//    PolygonFace AllPolygons[];
//};
